export const TWEETS_NEXT_PAGE = 'TWEETS_NEXT_PAGE';
export const TWEETS_NEXT_PAGE_SUCCEEDED = 'TWEETS_NEXT_PAGE_SUCCEEDED';
export const TWEETS_NEXT_PAGE_FAILED = 'TWEETS_NEXT_PAGE_FAILED';
export const TWEETS_IS_EMPTY = 'TWEETS_IS_EMPTY';

export const TWEETS_RESET = 'TWEETS_RESET';
