export const RECOMMEND_TWEETS_NEXT_PAGE = 'RECOMMEND_NEXT_TWEET_PAGE';
export const RECOMMEND_TWEETS_NEXT_PAGE_SUCCEEDED = 'RECOMMEND_TWEETS_NEXT_PAGE_SUCCEEDED';
export const RECOMMEND_TWEETS_NEXT_PAGE_FAILED = 'RECOMMEND_TWEETS_NEXT_PAGE_FAILED';
export const RECOMMEND_TWEETS_RESET = 'RECOMMEND_TWEETS_RESET';
export const RECOMMEND_TWEETS_IS_EMPTY = 'RECOMMEND_TWEETS_IS_EMPTY';

export const RECOMMEND_USER_GET = 'RECOMMEND_USER_GET';
export const RECOMMEND_USER_GET_SUCCEEDED = 'RECOMMEND_USER_GET_SUCCEEDED';
export const RECOMMEND_USER_GET_FAILED = 'RECOMMEND_USER_GET_FAILED';
export const RESET_ALL = 'RESET_ALL';
