/**
 * 搜索
 */
export const USER_SEARCH_GET = 'USER_SEARCH_GET';
export const USER_SEARCH_GET_SUCCEEDED = 'USER_SEARCH_GET_SUCCEEDED';
export const USER_SEARCH_GET_FAILED = 'USER_SEARCH_GET_FAILED';

/**
 * 好友搜索
 */
export const FRIEND_SEARCH_GET = 'FRIEND_SEARCH_GET';
export const FRIEND_SEARCH_GET_SUCCEEDED = 'FRIEND_SEARCH_GET_SUCCEEDED';
export const FRIEND_SEARCH_GET_FAILED = 'FRIEND_SEARCH_GET_FAILED';

