

/**
 * 获取用户信息
 */
export const USER_INFO_GET = 'USER_INFO_GET';
export const USER_GET_SUCCEEDED = 'USER_GET_SUCCEEDED';
export const USER_GET_FAILED = 'USER_GET_SUCCEEDED';


/**
 * 获取用户关注对象
 */
export const USER_RELATIONS_GET = 'USER_RELATIONS_GET';
export const USER_RELATIONS_GET_SUCCEEDED = 'USER_RELATIONS_GET_SUCCEEDED';
export const USER_RELATIONS_GET_FAILED = 'USER_RELATIONS_GET_FAILED';


/**
 * 获取用户发表的推文信息
 */
export const USER_TWEETS_NEXT_PAGE = 'USER_TWEETS_NEXT_PAGE';
export const USER_TWEETS_NEXT_PAGE_SUCCEEDED = 'USER_TWEETS_NEXT_PAGE_SUCCEEDED';
export const USER_TWEETS_NEXT_PAGE_FAILED = 'USER_TWEETS_NEXT_PAGE_FAILED';
export const USER_TWEETS_IS_EMPTY = 'USER_TWEETS_IS_EMPTY';




/**
 * 清除
 */
export const USER_RESET_ALL = 'USER_RESET_ALL';


