/**
 * 弹窗按钮
 */
export const DIALOG_DISPLAY_SET = 'DIALOG_DISPLAY_SET';
export const DIALOG_BUTTONS_ELEM_SET = 'DIALOG_BUTTONS_ELEM_SET';


/**
 * tweet弹窗
 */
export const TWEET_FULL_CARD_ELEM_SET = 'TWEET_FULL_CARD_ELEM_SET';
export const TWEET_FULL_CARD_ELEM_SET_SUCCEEDED = 'TWEET_FULL_CARD_ELEM_SET_SUCCEEDED';
export const TWEET_FULL_CARD_ELEM_SET_FAILED = 'TWEET_FULL_CARD_ELEM_SET_FAILED';


/**
 * pub弹窗
 */
export const PUB_TRANSFER_UPLOAD = 'PUB_TRANSFER_UPLOAD';
export const PUB_TRANSFER_UPLOAD_SUCCEEDED = 'PUB_TRANSFER_UPLOAD_SUCCEEDED';
export const PUB_TRANSFER_UPLOAD_FAILED = 'PUB_TRANSFER_UPLOAD_FAILED';

export const PUB_TRANSFER_IMAGE_REMOVE = 'PUB_TRANSFER_IMAGE_REMOVE';
export const PUB_TRANSFER_IMAGE_REMOVE_SUCCEEDED = 'PUB_TRANSFER_IMAGE_REMOVE_SUCCEEDED';
export const PUB_TRANSFER_IMAGE_REMOVE_FAILED = 'PUB_TRANSFER_IMAGE_REMOVE_FAILED';

export const PUB_TRANSFER_RESET = 'PUB_TRANSFER_RESET';
export const PUB_TRANSFER_RESET_SUCCEEDED = 'PUB_TRANSFER_RESET_SUCCEEDED';
export const PUB_TRANSFER_RESET_FAILED = 'PUB_TRANSFER_RESET_FAILED';

export const PUB_UPLOAD = 'PUB_UPLOAD';
export const PUB_UPLOAD_SUCCEEDED = 'PUB_UPLOAD_SUCCEEDED';
export const PUB_UPLOAD_FAILED = 'PUB_UPLOAD_FAILED';




/**
 * 清除
 */
export const DIALOG_RESET_ALL = 'DIALOG_RESET_ALL';
export const DIALOG_RESET_ALL_SUCCEEDED = 'DIALOG_RESET_ALL_SUCCEEDED';
export const DIALOG_RESET_ALL_FAILED = 'DIALOG_RESET_ALL_FAILED';

export const UploadState = {
    before: 1,
    going: 2,
    done: 3,
};

export const UploadType = {
    image: 1,
    video: 2,
};


