/**
 * 弹窗信息
 */
export const DIALOG_DISPLAY_SET = 'DIALOG_DISPLAY_SET';
export const DIALOG_BUTTONS_ELEM_SET = 'DIALOG_BUTTONS_ELEM_SET';


export const TWEET_FULL_CARD_ELEM_SET = 'TWEET_FULL_CARD_ELEM_SET';
export const TWEET_FULL_CARD_ELEM_SET_SUCCEEDED = 'TWEET_FULL_CARD_ELEM_SET_SUCCEEDED';
export const TWEET_FULL_CARD_ELEM_SET_FAILD = 'TWEET_FULL_CARD_ELEM_SET_FAILD';


/**
 * 清除
 */
export const DIALOG_RESET_ALL = 'DIALOG_RESET_ALL';
