/**
 * Tweet Comment
 */
export const TWEET_COMMENT_LEAVE = 'TWEET_COMMENT_LEAVE';
export const TWEET_COMMENT_LEAVE_SUCCEEDED = 'TWEET_COMMENT_LEAVE_SUCCEEDED';
export const TWEET_COMMENT_LEAVE_FAILED = 'TWEET_COMMENT_LEAVE_FAILED';

export const TWEET_COMMENT_REMOVE = 'TWEET_COMMENT_REMOVE';
export const TWEET_COMMENT_REMOVE_SUCCEEDED = 'TWEET_COMMENT_REMOVE_SUCCEEDED';
export const TWEET_COMMENT_REMOVE_FAILED = 'TWEET_COMMENT_REMOVE_FAILED';

export const TWEET_COMMENT_NEXT_PAGE = 'TWEET_COMMENT_NEXT_PAGE';
export const TWEET_COMMENT_NEXT_PAGE_SUCCEEDED = 'TWEET_COMMENT_NEXT_PAGE_SUCCEEDED';
export const TWEET_COMMENT_NEXT_PAGE_FAILED = 'TWEET_COMMENT_NEXT_PAGE_FAILED';
export const TWEET_COMMENT_IS_EMPTY = 'TWEET_COMMENT_IS_EMPTY';




/**
 * Tweet Relations
 */
export const TWEET_RELATIONS_SET = 'TWEET_RELATIONS_SET';
export const TWEET_RELATIONS_SET_SUCCEEDED = 'TWEET_RELATIONS_SET_SUCCEEDED';
export const TWEET_RELATIONS_SET_FAILED = 'TWEET_RELATIONS_SET_FAILED';


/**
 * User Relations
 */
export const PERSON_RELATIONS_SET = 'USER_RELATIONS_SET';
export const PERSON_RELATIONS_SET_SUCCEEDED = 'USER_RELATIONS_SET_SUCCEEDED';
export const PERSON_RELATIONS_SET_FAILED = 'USER_RELATIONS_SET_FAILED';

/**
 * refresh
 */

export const RELATIONS_REFRESH_DONE = 'RELATIONS_REFRESH_DONE'